network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      addresses:
        - 128.254.206.44/24
        - 217.217.223.2/24
        - 217.217.223.3/24
        - 217.217.223.4/24
        - 217.217.223.5/24
        - 217.217.223.6/24
        - 217.217.223.7/24
        - 217.217.223.8/24
        - 217.217.223.9/24
        - 217.217.223.10/24
        - 217.217.223.11/24
        - 217.217.223.12/24
        - 217.217.223.13/24
        - 217.217.223.14/24
        - 217.217.223.15/24
        - 217.217.223.16/24
        - 217.217.223.17/24
        - 217.217.223.18/24
        - 217.217.223.19/24
        - 217.217.223.20/24
        - 217.217.223.21/24
        - 217.217.223.22/24
        - 217.217.223.23/24
        - 217.217.223.24/24
        - 217.217.223.25/24
        - 217.217.223.26/24
        - 217.217.223.27/24
        - 217.217.223.28/24
        - 217.217.223.29/24
        - 217.217.223.30/24
        - 217.217.223.31/24
        - 217.217.223.32/24
        - 217.217.223.33/24
        - 217.217.223.34/24
        - 217.217.223.35/24
        - 217.217.223.36/24
        - 217.217.223.37/24
        - 217.217.223.38/24
        - 217.217.223.39/24
        - 217.217.223.40/24
        - 217.217.223.41/24
        - 217.217.223.42/24
        - 217.217.223.43/24
        - 217.217.223.44/24
        - 217.217.223.45/24
        - 217.217.223.46/24
        - 217.217.223.47/24
        - 217.217.223.48/24
        - 217.217.223.49/24
        - 217.217.223.50/24
        - 217.217.223.51/24
        - 217.217.223.52/24
        - 217.217.223.53/24
        - 217.217.223.54/24
        - 217.217.223.55/24
        - 217.217.223.56/24
        - 217.217.223.57/24
        - 217.217.223.58/24
        - 217.217.223.59/24
        - 217.217.223.60/24
        - 217.217.223.61/24
        - 217.217.223.62/24
        - 217.217.223.63/24
        - 217.217.223.64/24
        - 217.217.223.65/24
        - 217.217.223.66/24
        - 217.217.223.67/24
        - 217.217.223.68/24
        - 217.217.223.69/24
        - 217.217.223.70/24
        - 217.217.223.71/24
        - 217.217.223.72/24
        - 217.217.223.73/24
        - 217.217.223.74/24
        - 217.217.223.75/24
        - 217.217.223.76/24
        - 217.217.223.77/24
        - 217.217.223.78/24
        - 217.217.223.79/24
        - 217.217.223.80/24
        - 217.217.223.81/24
        - 217.217.223.82/24
        - 217.217.223.83/24
        - 217.217.223.84/24
        - 217.217.223.85/24
        - 217.217.223.86/24
        - 217.217.223.87/24
        - 217.217.223.88/24
        - 217.217.223.89/24
        - 217.217.223.90/24
        - 217.217.223.91/24
        - 217.217.223.92/24
        - 217.217.223.93/24
        - 217.217.223.94/24
        - 217.217.223.95/24
        - 217.217.223.96/24
        - 217.217.223.97/24
        - 217.217.223.98/24
        - 217.217.223.99/24
        - 217.217.223.100/24
        - 217.217.223.101/24
        - 217.217.223.102/24
        - 217.217.223.103/24
        - 217.217.223.104/24
        - 217.217.223.105/24
        - 217.217.223.106/24
        - 217.217.223.107/24
        - 217.217.223.108/24
        - 217.217.223.109/24
        - 217.217.223.110/24
        - 217.217.223.111/24
        - 217.217.223.112/24
        - 217.217.223.113/24
        - 217.217.223.114/24
        - 217.217.223.115/24
        - 217.217.223.116/24
        - 217.217.223.117/24
        - 217.217.223.118/24
        - 217.217.223.119/24
        - 217.217.223.120/24
        - 217.217.223.121/24
        - 217.217.223.122/24
        - 217.217.223.123/24
        - 217.217.223.124/24
        - 217.217.223.125/24
        - 217.217.223.126/24
        - 217.217.223.127/24
        - 217.217.223.128/24
        - 217.217.223.129/24
        - 217.217.223.130/24
        - 217.217.223.131/24
        - 217.217.223.132/24
        - 217.217.223.133/24
        - 217.217.223.134/24
        - 217.217.223.135/24
        - 217.217.223.136/24
        - 217.217.223.137/24
        - 217.217.223.138/24
        - 217.217.223.139/24
        - 217.217.223.140/24
        - 217.217.223.141/24
        - 217.217.223.142/24
        - 217.217.223.143/24
        - 217.217.223.144/24
        - 217.217.223.145/24
        - 217.217.223.146/24
        - 217.217.223.147/24
        - 217.217.223.148/24
        - 217.217.223.149/24
        - 217.217.223.150/24
        - 217.217.223.151/24
        - 217.217.223.152/24
        - 217.217.223.153/24
        - 217.217.223.154/24
        - 217.217.223.155/24
        - 217.217.223.156/24
        - 217.217.223.157/24
        - 217.217.223.158/24
        - 217.217.223.159/24
        - 217.217.223.160/24
        - 217.217.223.161/24
        - 217.217.223.162/24
        - 217.217.223.163/24
        - 217.217.223.164/24
        - 217.217.223.165/24
        - 217.217.223.166/24
        - 217.217.223.167/24
        - 217.217.223.168/24
        - 217.217.223.169/24
        - 217.217.223.170/24
        - 217.217.223.171/24
        - 217.217.223.172/24
        - 217.217.223.173/24
        - 217.217.223.174/24
        - 217.217.223.175/24
        - 217.217.223.176/24
        - 217.217.223.177/24
        - 217.217.223.178/24
        - 217.217.223.179/24
        - 217.217.223.180/24
        - 217.217.223.181/24
        - 217.217.223.182/24
        - 217.217.223.183/24
        - 217.217.223.184/24
        - 217.217.223.185/24
        - 217.217.223.186/24
        - 217.217.223.187/24
        - 217.217.223.188/24
        - 217.217.223.189/24
        - 217.217.223.190/24
        - 217.217.223.191/24
        - 217.217.223.192/24
        - 217.217.223.193/24
        - 217.217.223.194/24
        - 217.217.223.195/24
        - 217.217.223.196/24
        - 217.217.223.197/24
        - 217.217.223.198/24
        - 217.217.223.199/24
        - 217.217.223.200/24
        - 217.217.223.201/24
        - 217.217.223.202/24
        - 217.217.223.203/24
        - 217.217.223.204/24
        - 217.217.223.205/24
        - 217.217.223.206/24
        - 217.217.223.207/24
        - 217.217.223.208/24
        - 217.217.223.209/24
        - 217.217.223.210/24
        - 217.217.223.211/24
        - 217.217.223.212/24
        - 217.217.223.213/24
        - 217.217.223.214/24
        - 217.217.223.215/24
        - 217.217.223.216/24
        - 217.217.223.217/24
        - 217.217.223.218/24
        - 217.217.223.219/24
        - 217.217.223.220/24
        - 217.217.223.221/24
        - 217.217.223.222/24
        - 217.217.223.223/24
        - 217.217.223.224/24
        - 217.217.223.225/24
        - 217.217.223.226/24
        - 217.217.223.227/24
        - 217.217.223.228/24
        - 217.217.223.229/24
        - 217.217.223.230/24
        - 217.217.223.231/24
        - 217.217.223.232/24
        - 217.217.223.233/24
        - 217.217.223.234/24
        - 217.217.223.235/24
        - 217.217.223.236/24
        - 217.217.223.237/24
        - 217.217.223.238/24
        - 217.217.223.239/24
        - 217.217.223.240/24
        - 217.217.223.241/24
        - 217.217.223.242/24
        - 217.217.223.243/24
        - 217.217.223.244/24
        - 217.217.223.245/24
        - 217.217.223.246/24
        - 217.217.223.247/24
        - 217.217.223.248/24
        - 217.217.223.249/24
        - 217.217.223.250/24
        - 217.217.223.251/24
        - 217.217.223.252/24
        - 217.217.223.253/24
        - 217.217.223.254/24
      gateway4: 128.254.206.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
